### PR TITLE
Feature: Product listing

### LINKED ISSUE #2: Epic: Product listing page
# Product listing page

Feature: Product listing page

## Epic Description

This Feature will complete the product listing page, with filters and products card.

### Home page

- [ ] Show all products
- [ ] Product card should contain add to cart
- [ ] Product card should contain wishlist button

### Filters

- [ ] Price
- [ ] Category
- [ ] Rating
- [ ] Clear filters button

### PR DESCRIPTION
**Pull request by Pratham82**
# Product listing page

[Epic: Product listing page #2](https://github.com/Pratham82/e-comm-react/issues/2)

## Changes made

- [x] Update product listing and homepage styles
- [x] Added mock endpoints with mockbee
- [x] Added filter and data source context
- [x] Added filters,sorting feature in product listing
- [x] Abstracted out common components

## How does the solution address the problem

This PR will resolve the issue 2

## Linked issues

Resolves #2

### CODE REVIEW

**Review by sashaboi — APPROVED** [review]
Everything looks amazing! 
maybe adding a link directly to the products page in the pr itself might help ppl skip homepage, as i see there is some work to be done there yet, images look wonky on my screen.

looks good to merge for products page.

**Comment by sashaboi** [comment]
homepage looks like this to me on a 1920-1080 screen 
image

**Comment by Pratham82** [comment]
Yes, I still need to work on the homepage, I'll fix that. Thanks for the review

**Comment by ashifkhn** [comment]
Pretty clean. Good to go

**Pull request merged**
